---
version: 4
---
```typescript
console.trace();
```

######
```json - error
Trace: 
    at error - console trace.notebook:5:13
    at C:\projects\data-forge-notebook\data-forge-notebook-git\src\common\code-evaluator\code-evaluator.ts:585:17
    at AsyncResource.runInAsyncScope (async_hooks.js:173:16)
    at CodeEvaluator.__cell (C:\projects\data-forge-notebook\data-forge-notebook-git\src\common\code-evaluator\code-evaluator.ts:577:26)
    at wrapperFn (error - console trace.notebook:4:3)
    at error - console trace.notebook:9:10
    at CodeEvaluator.evalGeneratedCode (C:\projects\data-forge-notebook\data-forge-notebook-git\src\common\code-evaluator\code-evaluator.ts:621:13)
    at C:\projects\data-forge-notebook\data-forge-notebook-git\src\common\code-evaluator\code-evaluator.ts:725:34
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```



